language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: RJhFd/bVJnfOmlNQPESFgU4nh6o5ELXsa5WHLE9gQEoSdWKcS1akCcsaW0Zc+jCMqWoXSe+2DMQQ5XkCeZ4NK6t29US+cLcXKFtt+QnB/hrNKyv/h3DbAvKdqsxXJko8JYeeseRcc+gtTOx8OF2FV4XJOk/j1qVxwSsay4PE/KAops1OziGXSnex4K+71KKvtpOx5Mo1dqfxs49gxBQUsymAAvo1B6OpVJtAID7dnOyyqNUKlbXoSrNb1O+3vl2nUoFD+Q67nmMi33iRCKOsAv0XjeGRsmkVqZDuHs1afvS6mWHGGfCvVFtXkT/YWZGPQm5y0Oc9x1pv1+J+MZT9O0fAlokkZfhld1qX6XB4UF+KE/0kjnINiAtQdXUA7tFlzCTK9u06AAZIyPFavSmgS5hPozAnEv/zYDKHbGolSL9+npcyj86VO6vI68N+/Dljx4BrMg9tA9sINszr5dTJHZ2AXAH6VGbonDyCLk6DBrNcrjzVbdPCp8o209xc0bG9q2Ewa7VVHiZQaK1ueatspL6iOAohZ9hVoZF0OyAmnaHLIYOpGLhVMvcPNahAL1Wen7f1+jxcUTGJfGv1wjEpTHPbXccrhjzB2BSllQ7s4ZTRUpPGmFB683rj2tq5asFRJicgfrtKaldnLLrqr0s3T1MSvglsjrTa725YfpVvNRg=
  app: peaceful-journey-75998
  run: rails db:migrate
  on:
    repo: Kathybui732/viewing_party
    branch: main
env:
  global:
    secure: OgyB64Oos/EL2M8ExTJHDhUUrIn2ODRnFZd5kd8PdnTh0YoTMLZdIguscjHhteEt2Bq0vJ8BFBHWhF3qLip3j3HO/Yxh/fhc055TXJuE9WIGgJyPLZkf3DIE7+9z5j5uJM1+f7CYMEfSVPcRTlQQNdByc7NJa+7tRoFlhPGeegL7k8Huvvdd/OWOwJkT38/qB0VwN8530HdcnHe9NeoDO0GEp1xdASf6WcY85leuOMutOqaaa6LlnA8nSMtp2Z0ntd8G438bsUeNtn7TaEZQFlC2g10bue+OC3EuxRGbcs0xu2l7kqfbkBVa0pZvWr4YrqKCFgSayc8jSFw5sWpQ43jRN9zJ2EZAq6Sdqg+dGPR2rorKr/U995ucePNRf/i7dyGXlKC6I6WP9Nv028b+F6X/WOfJ7wz1UQUPDa2YJ//hnNHzDIUMXrI/onMmsYZqGJE8R0/3fxpHrd0LKBkfzDsAlfF2ROK5P3MUFSMJtIqlG4YQGap9XPplI3KkJ7wvpkhYa2CA4ihVQ0Buw6+Evd3dWb7Asy5pbutfP2ImInGXV7foxOdtIBIW6xyEG8yuvWQY7zzgCHlQDbboJUEdN5BzTdXm70yc1jYmtQnVIwxUHYoGuM+Rlwufoqf99ebbZ+4dVooMaT3bIbtkZfT+yxOdg3KJ7bcyL2Bnq8P0csY=
