language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: mH/xQMhqwSiVYoTHEiXqaLXa+G8z3I90UDcjBxRIBrqFLe/U6m0xW/cqIds/gdbAJreb72UqlvWW9yrgPqKxqmjDIuxeK7K9/qLuhq2+ly1+HJIG4lSJwem4wskkia9lMVW6FqsDsA+XeAZCw11bpiuM+7E+p4h55TPymGUZyMtH8towx0fwBarG2918GRXItPYpjxTlqOSVb5AWx1o8qnFXOr0oQu7stx22RDiJBC//TCbEsHA80skt2ihEZ3ApBV8PoSeQALTbAuoUeET2Zi05JhnqwRd4Frf6lOrza5Ilu0ATL5IbdBaICxq8n1wr0jqZGqBqANw2usYfeaSdAAi5DRLiJn8ANPpk5rJv3ASqF4otDZED5skRnkl53VK80e46S0JMIRHMeNheeX608mL0GNPEWX2AK4omQ6SFI0GP8Fpcfwjw/ylmXNF9b54LlyHQosHLvzD0zuKXpQe377EjpV1GEuM4WubNg4qVxfXMHioUAbq49GcojLxH8sIWtrXsic0L7O1NBObZFXAMbXTrHe77bsFAjxZ1kOLmxR6Z+Utxoyh3k0x6nw6o3ZYKfjJGP0HtHT1Xuq17Rfquyugvv+qdnnRHngmEf2TatTwfnmF18XeV9jOeq1wrh6mIrzaFHqzB3MCi6iSU9qwZumDzciHR3JnA7DWTX+9mopY=
  app: sheltered-chamber-43475
  run: rails db:migrate
  on:
    repo: Kathybui732/viewing_party
    branch: main
env:
  global:
    secure: OgyB64Oos/EL2M8ExTJHDhUUrIn2ODRnFZd5kd8PdnTh0YoTMLZdIguscjHhteEt2Bq0vJ8BFBHWhF3qLip3j3HO/Yxh/fhc055TXJuE9WIGgJyPLZkf3DIE7+9z5j5uJM1+f7CYMEfSVPcRTlQQNdByc7NJa+7tRoFlhPGeegL7k8Huvvdd/OWOwJkT38/qB0VwN8530HdcnHe9NeoDO0GEp1xdASf6WcY85leuOMutOqaaa6LlnA8nSMtp2Z0ntd8G438bsUeNtn7TaEZQFlC2g10bue+OC3EuxRGbcs0xu2l7kqfbkBVa0pZvWr4YrqKCFgSayc8jSFw5sWpQ43jRN9zJ2EZAq6Sdqg+dGPR2rorKr/U995ucePNRf/i7dyGXlKC6I6WP9Nv028b+F6X/WOfJ7wz1UQUPDa2YJ//hnNHzDIUMXrI/onMmsYZqGJE8R0/3fxpHrd0LKBkfzDsAlfF2ROK5P3MUFSMJtIqlG4YQGap9XPplI3KkJ7wvpkhYa2CA4ihVQ0Buw6+Evd3dWb7Asy5pbutfP2ImInGXV7foxOdtIBIW6xyEG8yuvWQY7zzgCHlQDbboJUEdN5BzTdXm70yc1jYmtQnVIwxUHYoGuM+Rlwufoqf99ebbZ+4dVooMaT3bIbtkZfT+yxOdg3KJ7bcyL2Bnq8P0csY=
